version: "3.3"

services:
  marzban:
    image: gozargah/marzban:latest
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://marzban:MarzbanPass123!@localhost:5433/marzban
      - SQLALCHEMY_DATABASE_URL=postgresql://marzban:MarzbanPass123!@localhost:5433/marzban
    network_mode: host
    volumes:
      - /var/lib/marzban:/var/lib/marzban
    depends_on:
      - marzban-db

  marzban-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: marzban
      POSTGRES_USER: marzban
      POSTGRES_PASSWORD: MarzbanPass123!
      PGDATA: /var/lib/postgresql/data
    network_mode: host
    volumes:
      - /var/lib/marzban-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marzban -d marzban"]
      interval: 10s
      timeout: 5s
      retries: 5
